import type { Professional, Service, Client, Appointment, Transaction, DashboardMetrics } from '@/types';

export const mockProfessionals: Professional[] = [
  {
    id: '1',
    tenantId: '1',
    userId: '1',
    name: 'Ana Silva',
    email: 'ana@azzo.com',
    phone: '(11) 99999-1111',
    avatar: 'https://mgx-backend-cdn.metadl.com/generate/images/968095/2026-02-12/6c476f2a-8002-4ffb-8394-c90ae976f88c.png',
    specialties: ['Corte Feminino', 'Coloração', 'Escova'],
    commissionRate: 40,
    workingHours: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '18:00', isWorking: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '18:00', isWorking: true },
      { dayOfWeek: 3, startTime: '09:00', endTime: '18:00', isWorking: true },
      { dayOfWeek: 4, startTime: '09:00', endTime: '18:00', isWorking: true },
      { dayOfWeek: 5, startTime: '09:00', endTime: '18:00', isWorking: true },
      { dayOfWeek: 6, startTime: '09:00', endTime: '14:00', isWorking: true },
      { dayOfWeek: 0, startTime: '00:00', endTime: '00:00', isWorking: false },
    ],
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    tenantId: '1',
    userId: '2',
    name: 'Carlos Santos',
    email: 'carlos@azzo.com',
    phone: '(11) 99999-2222',
    specialties: ['Corte Masculino', 'Barba', 'Pigmentação'],
    commissionRate: 35,
    workingHours: [
      { dayOfWeek: 1, startTime: '10:00', endTime: '19:00', isWorking: true },
      { dayOfWeek: 2, startTime: '10:00', endTime: '19:00', isWorking: true },
      { dayOfWeek: 3, startTime: '10:00', endTime: '19:00', isWorking: true },
      { dayOfWeek: 4, startTime: '10:00', endTime: '19:00', isWorking: true },
      { dayOfWeek: 5, startTime: '10:00', endTime: '19:00', isWorking: true },
      { dayOfWeek: 6, startTime: '10:00', endTime: '15:00', isWorking: true },
      { dayOfWeek: 0, startTime: '00:00', endTime: '00:00', isWorking: false },
    ],
    isActive: true,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '3',
    tenantId: '1',
    userId: '3',
    name: 'Juliana Costa',
    email: 'juliana@azzo.com',
    phone: '(11) 99999-3333',
    specialties: ['Manicure', 'Pedicure', 'Unhas em Gel'],
    commissionRate: 45,
    workingHours: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '17:00', isWorking: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '17:00', isWorking: true },
      { dayOfWeek: 3, startTime: '09:00', endTime: '17:00', isWorking: true },
      { dayOfWeek: 4, startTime: '09:00', endTime: '17:00', isWorking: true },
      { dayOfWeek: 5, startTime: '09:00', endTime: '17:00', isWorking: true },
      { dayOfWeek: 6, startTime: '00:00', endTime: '00:00', isWorking: false },
      { dayOfWeek: 0, startTime: '00:00', endTime: '00:00', isWorking: false },
    ],
    isActive: true,
    createdAt: new Date('2024-03-10'),
  },
];

export const mockServices: Service[] = [
  {
    id: '1',
    tenantId: '1',
    name: 'Corte Feminino',
    description: 'Corte de cabelo feminino com lavagem e finalização',
    duration: 60,
    price: 80,
    category: 'Cabelo',
    professionalIds: ['1'],
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    tenantId: '1',
    name: 'Corte Masculino',
    description: 'Corte de cabelo masculino com lavagem',
    duration: 30,
    price: 45,
    category: 'Cabelo',
    professionalIds: ['2'],
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    tenantId: '1',
    name: 'Coloração',
    description: 'Coloração completa com produtos de qualidade',
    duration: 120,
    price: 180,
    category: 'Cabelo',
    professionalIds: ['1'],
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '4',
    tenantId: '1',
    name: 'Escova',
    description: 'Escova modeladora com finalização',
    duration: 45,
    price: 60,
    category: 'Cabelo',
    professionalIds: ['1'],
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '5',
    tenantId: '1',
    name: 'Barba',
    description: 'Barba completa com toalha quente',
    duration: 30,
    price: 35,
    category: 'Barba',
    professionalIds: ['2'],
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '6',
    tenantId: '1',
    name: 'Manicure',
    description: 'Manicure completa com esmaltação',
    duration: 45,
    price: 40,
    category: 'Unhas',
    professionalIds: ['3'],
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '7',
    tenantId: '1',
    name: 'Pedicure',
    description: 'Pedicure completa com esmaltação',
    duration: 60,
    price: 50,
    category: 'Unhas',
    professionalIds: ['3'],
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '8',
    tenantId: '1',
    name: 'Unhas em Gel',
    description: 'Aplicação de unhas em gel com design',
    duration: 90,
    price: 120,
    category: 'Unhas',
    professionalIds: ['3'],
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
];

export const mockClients: Client[] = [
  {
    id: '1',
    tenantId: '1',
    name: 'Maria Oliveira',
    email: 'maria@email.com',
    phone: '(11) 98888-1111',
    birthDate: new Date('1990-05-15'),
    notes: 'Prefere horários pela manhã',
    totalVisits: 12,
    totalSpent: 1450,
    lastVisit: new Date('2026-02-10'),
    createdAt: new Date('2024-06-01'),
  },
  {
    id: '2',
    tenantId: '1',
    name: 'João Pereira',
    email: 'joao@email.com',
    phone: '(11) 98888-2222',
    birthDate: new Date('1985-08-20'),
    totalVisits: 8,
    totalSpent: 640,
    lastVisit: new Date('2026-02-08'),
    createdAt: new Date('2024-07-15'),
  },
  {
    id: '3',
    tenantId: '1',
    name: 'Fernanda Lima',
    email: 'fernanda@email.com',
    phone: '(11) 98888-3333',
    birthDate: new Date('1995-12-03'),
    notes: 'Alérgica a alguns produtos químicos',
    totalVisits: 5,
    totalSpent: 890,
    lastVisit: new Date('2026-02-05'),
    createdAt: new Date('2024-09-20'),
  },
  {
    id: '4',
    tenantId: '1',
    name: 'Roberto Alves',
    email: 'roberto@email.com',
    phone: '(11) 98888-4444',
    totalVisits: 15,
    totalSpent: 1200,
    lastVisit: new Date('2026-02-11'),
    createdAt: new Date('2024-04-10'),
  },
  {
    id: '5',
    tenantId: '1',
    name: 'Camila Souza',
    email: 'camila@email.com',
    phone: '(11) 98888-5555',
    birthDate: new Date('1992-03-28'),
    totalVisits: 3,
    totalSpent: 320,
    lastVisit: new Date('2026-01-28'),
    createdAt: new Date('2024-11-05'),
  },
];

const today = new Date();
const createDateWithOffset = (daysOffset: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + daysOffset);
  return date;
};

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    tenantId: '1',
    clientId: '1',
    client: mockClients[0],
    professionalId: '1',
    professional: mockProfessionals[0],
    serviceId: '1',
    service: mockServices[0],
    date: createDateWithOffset(0),
    startTime: '09:00',
    endTime: '10:00',
    status: 'CONFIRMED',
    totalPrice: 80,
    createdAt: new Date(),
  },
  {
    id: '2',
    tenantId: '1',
    clientId: '2',
    client: mockClients[1],
    professionalId: '2',
    professional: mockProfessionals[1],
    serviceId: '2',
    service: mockServices[1],
    date: createDateWithOffset(0),
    startTime: '10:00',
    endTime: '10:30',
    status: 'CONFIRMED',
    totalPrice: 45,
    createdAt: new Date(),
  },
  {
    id: '3',
    tenantId: '1',
    clientId: '3',
    client: mockClients[2],
    professionalId: '3',
    professional: mockProfessionals[2],
    serviceId: '6',
    service: mockServices[5],
    date: createDateWithOffset(0),
    startTime: '11:00',
    endTime: '11:45',
    status: 'PENDING',
    totalPrice: 40,
    createdAt: new Date(),
  },
  {
    id: '4',
    tenantId: '1',
    clientId: '4',
    client: mockClients[3],
    professionalId: '2',
    professional: mockProfessionals[1],
    serviceId: '5',
    service: mockServices[4],
    date: createDateWithOffset(0),
    startTime: '14:00',
    endTime: '14:30',
    status: 'CONFIRMED',
    totalPrice: 35,
    createdAt: new Date(),
  },
  {
    id: '5',
    tenantId: '1',
    clientId: '1',
    client: mockClients[0],
    professionalId: '1',
    professional: mockProfessionals[0],
    serviceId: '3',
    service: mockServices[2],
    date: createDateWithOffset(0),
    startTime: '15:00',
    endTime: '17:00',
    status: 'PENDING',
    totalPrice: 180,
    createdAt: new Date(),
  },
  {
    id: '6',
    tenantId: '1',
    clientId: '5',
    client: mockClients[4],
    professionalId: '3',
    professional: mockProfessionals[2],
    serviceId: '8',
    service: mockServices[7],
    date: createDateWithOffset(1),
    startTime: '10:00',
    endTime: '11:30',
    status: 'CONFIRMED',
    totalPrice: 120,
    createdAt: new Date(),
  },
  {
    id: '7',
    tenantId: '1',
    clientId: '2',
    client: mockClients[1],
    professionalId: '2',
    professional: mockProfessionals[1],
    serviceId: '2',
    service: mockServices[1],
    date: createDateWithOffset(1),
    startTime: '11:00',
    endTime: '11:30',
    status: 'PENDING',
    totalPrice: 45,
    createdAt: new Date(),
  },
  {
    id: '8',
    tenantId: '1',
    clientId: '3',
    client: mockClients[2],
    professionalId: '1',
    professional: mockProfessionals[0],
    serviceId: '4',
    service: mockServices[3],
    date: createDateWithOffset(2),
    startTime: '09:00',
    endTime: '09:45',
    status: 'CONFIRMED',
    totalPrice: 60,
    createdAt: new Date(),
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    tenantId: '1',
    appointmentId: '1',
    type: 'INCOME',
    category: 'Serviço',
    description: 'Corte Feminino - Maria Oliveira',
    amount: 80,
    paymentMethod: 'PIX',
    date: createDateWithOffset(-1),
    createdAt: new Date(),
  },
  {
    id: '2',
    tenantId: '1',
    appointmentId: '2',
    type: 'INCOME',
    category: 'Serviço',
    description: 'Corte Masculino - João Pereira',
    amount: 45,
    paymentMethod: 'CREDIT_CARD',
    date: createDateWithOffset(-1),
    createdAt: new Date(),
  },
  {
    id: '3',
    tenantId: '1',
    type: 'EXPENSE',
    category: 'Produtos',
    description: 'Compra de shampoos e condicionadores',
    amount: 350,
    paymentMethod: 'DEBIT_CARD',
    date: createDateWithOffset(-2),
    createdAt: new Date(),
  },
  {
    id: '4',
    tenantId: '1',
    type: 'INCOME',
    category: 'Serviço',
    description: 'Coloração - Fernanda Lima',
    amount: 180,
    paymentMethod: 'PIX',
    date: createDateWithOffset(-2),
    createdAt: new Date(),
  },
  {
    id: '5',
    tenantId: '1',
    type: 'EXPENSE',
    category: 'Aluguel',
    description: 'Aluguel do mês',
    amount: 2500,
    paymentMethod: 'OTHER',
    date: createDateWithOffset(-5),
    createdAt: new Date(),
  },
  {
    id: '6',
    tenantId: '1',
    type: 'INCOME',
    category: 'Serviço',
    description: 'Unhas em Gel - Camila Souza',
    amount: 120,
    paymentMethod: 'CASH',
    date: createDateWithOffset(-3),
    createdAt: new Date(),
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  todayAppointments: 5,
  todayRevenue: 380,
  monthlyRevenue: 12450,
  totalClients: 156,
  pendingAppointments: 2,
  completedToday: 3,
  notConcludedToday: 11,
  stoppedAtServiceSelection: 4,
  stoppedAtProfessionalSelection: 3,
  stoppedAtTimeSelection: 2,
  stoppedAtFinalReview: 2,
};

export const getStatusColor = (status: string) => {
  const colors: Record<string, string> = {
    PENDING: 'bg-amber-100 text-amber-800',
    CONFIRMED: 'bg-blue-100 text-blue-800',
    IN_PROGRESS: 'bg-purple-100 text-purple-800',
    COMPLETED: 'bg-green-100 text-green-800',
    CANCELLED: 'bg-red-100 text-red-800',
    NO_SHOW: 'bg-gray-100 text-gray-800',
  };
  return colors[status] || 'bg-gray-100 text-gray-800';
};

export const getStatusLabel = (status: string) => {
  const labels: Record<string, string> = {
    PENDING: 'Pendente',
    CONFIRMED: 'Confirmado',
    IN_PROGRESS: 'Em Andamento',
    COMPLETED: 'Concluído',
    CANCELLED: 'Cancelado',
    NO_SHOW: 'Não Compareceu',
  };
  return labels[status] || status;
};

export const getPaymentMethodLabel = (method: string) => {
  const labels: Record<string, string> = {
    CASH: 'Dinheiro',
    CREDIT_CARD: 'Cartão de Crédito',
    DEBIT_CARD: 'Cartão de Débito',
    PIX: 'Pix',
    OTHER: 'Outro',
  };
  return labels[method] || method;
};

export const formatCurrency = (value: number) => {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL',
  }).format(value);
};

export const formatDate = (date: Date) => {
  return new Intl.DateTimeFormat('pt-BR', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  }).format(date);
};

export const formatTime = (time: string) => {
  return time;
};
