export const appRouteManifest = {
  public: {
    root: "/",
    login: "/login",
    forgotPassword: "/recuperar-senha",
    resetPassword: "/redefinir-senha",
    register: "/cadastro",
    publicBooking: "/agendar/:slug",
    termsOfUse: "/termos-de-uso",
    privacyPolicy: "/politica-privacidade",
    sales: "/compras",
    salesProduct: "/compras/:productId",
    checkoutSuccess: "/success",
    checkoutError: "/error",
  },
  shell: {
    dashboard: "/dashboard",
    notifications: "/notificacoes",
    agenda: "/agenda",
    suggestions: "/sugestoes",
    unauthorized: "/unauthorized",
  },
  reports: {
    root: "/relatorio",
    appointments: "/relatorio/agendamento",
    noShow: "/relatorio/no-show",
    abandonment: "/relatorio/abandono",
    legacyRoot: "/relatorios",
    legacyAppointments: "/relatorios/agendamento",
    legacyAppointmentsPlural: "/relatorios/agendamentos",
    legacyNoShow: "/relatorios/no-show",
    legacyAbandonment: "/relatorios/abandono",
    agendaNoShow: "/agenda/no-show",
    agendaNoShowWildcard: "/agenda/no-show/*",
  },
  services: {
    root: "/servicos",
    imports: "importacoes",
    importDetail: "importacoes/:jobId",
  },
  specialties: {
    root: "/especialidades",
    imports: "importacoes",
    importDetail: "importacoes/:jobId",
  },
  professionals: {
    root: "/profissionais",
    profile: "/profissionais/:id",
    commission: "/profissionais/:id/comissao",
  },
  clients: {
    root: "/clientes",
    profile: "/clientes/:id",
    imports: "importacoes",
    importDetail: "importacoes/:jobId",
  },
  chat: {
    root: "/chat",
    conversation: "/chat/:conversationId",
  },
  stock: {
    root: "/estoque",
    overview: "visao-geral",
    items: "itens",
    itemCreate: "itens/novo",
    itemEdit: "itens/:id/editar",
    movements: "movimentacoes",
    movementCreate: "movimentacoes/nova",
    imports: "importacoes",
    importDetail: "importacoes/:jobId",
    inventories: "inventarios",
    inventoryCreate: "inventarios/novo",
    inventoryDetail: "inventarios/:id",
    suppliers: "fornecedores",
    purchaseOrders: "pedidos-compra",
    purchaseOrderDetail: "pedidos-compra/:id",
    transfers: "transferencias",
    settingsAlias: "configuracoes",
  },
  finance: {
    root: "/financeiro",
    commissions: "/financeiro/comissoes",
    professionalCommission: "/financeiro/comissoes/:professionalId",
    professionals: "/financeiro/profissionais",
    license: "/financeiro/licenca",
  },
  audit: {
    root: "/auditoria",
    lgpd: "/auditoria/lgpd",
  },
  settings: {
    root: "/configuracoes",
    stock: "/configuracoes/estoque",
    fiscalTaxes: "/configuracoes/fiscal/impostos",
    fiscalCertificates: "/configuracoes/fiscal/certificados",
    fiscalNfse: "/configuracoes/fiscal/nfse",
    whatsapp: "/configuracoes/integracoes/whatsapp",
    systemAdmin: "/configuracoes/admin-sistema",
  },
  profiles: {
    user: "/perfil-usuario",
    salon: "/perfil-salao",
  },
  fiscal: {
    invoices: "/fiscal/nfse",
    invoiceCreate: "/fiscal/nfse/nova",
    invoiceDetail: "/fiscal/nfse/:id",
    invoiceEdit: "/fiscal/nfse/:id/editar",
    invoicePdf: "/fiscal/nfse/:id/pdf",
    taxAlias: "/config-impostos",
    invoicePreview: "/nota-fiscal",
    invoiceEmission: "/emitir-nota",
    monthlyTaxStatement: "/apuracao-mensal",
  },
} as const;

export const defaultProtectedRouteByRole = {
  PROFESSIONAL: appRouteManifest.shell.agenda,
  DEFAULT: appRouteManifest.shell.dashboard,
} as const;

export const preferredProtectedRoutesByRole = {
  PROFESSIONAL: [
    appRouteManifest.shell.agenda,
    appRouteManifest.clients.root,
    appRouteManifest.chat.root,
    appRouteManifest.shell.suggestions,
    appRouteManifest.shell.notifications,
  ],
  DEFAULT: [appRouteManifest.shell.dashboard],
} as const;
